export const PROXY_USERS = [
  { username: "lowlight", email: "lowlight@voice.community", previous: "lena_hart" },
  { username: "afterglow", email: "afterglow@voice.community", previous: "james_okoye" },
  { username: "paperthin", email: "paperthin@voice.community", previous: "priya_nair" },
  { username: "stillwater", email: "stillwater@voice.community", previous: "noah_ellison" },
  { username: "nightjar", email: "nightjar@voice.community", previous: "sofia_reyes" },
  { username: "inkrest", email: "inkrest@voice.community", previous: "marcus_dale" },
  { username: "fogline", email: "fogline@voice.community", previous: "amira_soltani" },
  { username: "coldtea", email: "coldtea@voice.community", previous: "owen_briggs" },
  { username: "lasttrain", email: "lasttrain@voice.community", previous: "hana_mori" },
  { username: "softiron", email: "softiron@voice.community", previous: "daniel_cho" },
  { username: "mae", email: "mae@voice.community", previous: "isla_bennett" },
  { username: "nico", email: "nico@voice.community", previous: "rafael_costa" },
  { username: "jules", email: "jules@voice.community", previous: "nina_volkov" },
  { username: "rory", email: "rory@voice.community", previous: "theo_anders" },
  { username: "eden", email: "eden@voice.community", previous: "camille_dubois" },
  { username: "wren", email: "wren@voice.community", previous: "arjun_mehta" },
  { username: "kit", email: "kit@voice.community", previous: "eliza_ward" },
  { username: "reed", email: "reed@voice.community", previous: "samir_haddad" },
  { username: "cole", email: "cole@voice.community", previous: "claire_nguyen" },
  { username: "ivy", email: "ivy@voice.community", previous: "leo_vasquez" },
  { username: "ash", email: "ash@voice.community", previous: "ruby_santiago" },
  { username: "noa", email: "noa@voice.community", previous: "ethan_brooks" },
  { username: "vale", email: "vale@voice.community", previous: "aisha_khalil" },
  { username: "hush", email: "hush@voice.community", previous: "peter_lang" },
];
